---
################################################################
###                    *** WARNING ***
################################################################
###
### ALMOST EVERYTHING REQUESTED IN THIS FILE ARE CONFIDENTIAL CREDENTIALS
### IF YOU POST THIS FILE ONLINE (such as on GitHub) YOUR BOT COULD BE COMPROMISED
###
###
### Use a proper text editor when editing this file, for example Sublime.
### Do not use tab characters in this file, use plain spaces.
###
### Keep at least one space after a colon, like so:
###
###   key: value
###
###
### You can wrap most values into quotation marks, except numbers and booleans:
###
###   someUrl: "http://example.com"
###   someToken: "123.qwe.456[DFG="
###   somePortNumber: 22
###   useSomeFeature: true
###
###
### You can have a list of things like this:
###
###   listOfStrings: ["string1", "string2", "string3"]
###
### or like this:
###
###   listOfStrings:
###     - "string1"
###     - "string2"
###     - "string3"
###
###
### More information on correctly formatting yaml files: http://www.yaml.org/start.html

spring:
  http:
    converters:
      preferred-json-mapper: gson # dont touch this
server:
  port: 4269

security:
  admins:
    # Set a name and a pass. These have to be the same as set up in the fredboat.yaml
    # Do not leave any of them blank or empty.
    - name: ""
      pass: ""


database:
  main:
    # FredBoat was written to work with PostgreSQL.
    # If you are running with docker-compose then you don't need to change the jdbcUrl here.
    # In PostgreSQL, role means user and vice versa. Keep that in mind when reading the following help and the provided links.
    # If you are running your own PostgreSQL database, you will need to provide a role and a database belonging to that role.
    # The role needs at least the permission to log in.
    # All postgres databases used by FredBoat are required to have the Hstore extension enabled.
    # Learn more about roles here: https://www.postgresql.org/docs/10/static/database-roles.html
    # Learn more about creating databases here: https://www.postgresql.org/docs/10/static/manage-ag-createdb.html
    # Learn more about the postgres jdbc url here: https://jdbc.postgresql.org/documentation/head/connect.html
    # Learn more about creating extensions here: https://www.postgresql.org/docs/current/static/sql-createextension.html
    # If you are using an SSH tunnel, you need to point your jdbc url to localhost and the configured tunnelLocalPort
    # Example jdbc: "jdbc:postgresql://localhost:5432/fredboat?user=fredboat&password=youshallnotpass"
    jdbcUrl:          ""

    # Ssh tunnel for a remote database. this is useful for when you don't want to expose your database on the remote server
    # and instead use ssh tunneling to access it
    # If you are running with docker-compose then you don't need to change any ssh value here.
    # If you are using an SSH tunnel, you need to point your jdbc url to localhost and the configured tunnelLocalPort
    # Keep the sshHost an empty string for no tunnel.
    tunnel:
      host:           ""         # add the ssh port to the ip / url, usually 22, for example: "db.example.com:22"
      user:           ""         # user on the remote machine
      privateKeyFile: ""         # path to an ssh private key file which is authorized to log in to the sshUser on the remote machine. learn how to create these: https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04#step-four-—-add-public-key-authentication-(recommended)
      keyPass:        ""         # optional passphrase for the ssh key file
      localPort:      5432       # endpoint port of the tunnel on the machine running fredboat; makes sure these dont collide; this one needs to be used in the jdbc url
      remotePort:     5432       # port of the PostgreSQL on the remote machine, 5432 by default

  cache:
    # Database for caching things, see config of main database above for details about the individual values.
    # If you are running with docker-compose then you don't need to change the cache jdbcUrl here.
    # The main and cache databases can be two databases inside a single postgres instance.
    # They CANNOT be the same database due to the way flyway migrations work.
    # The main benefit is that you don't have to backup/migrate the cache database, it can just be dropped/recreated
    # If you do not provide a jdbc url for the cache database, FredBoat will still work (most likely), but may have a degraded
    # performance, especially in high usage environments and when using Spotify playlists.
    # If you are going to use two different ssh tunnels for both database connections, make sure that the local tunnel ports don't collide
    jdbcUrl:          ""
    tunnel:
      host:           ""
      user:           ""
      privateKeyFile: ""
      keyPass:        ""
      localPort:      5433
      remotePort:     5432
